In [38]:
import pandas as pd
import numpy as np

In [3]:
pd.__version__

'1.3.2'

In [4]:
np.__version__

'1.19.5'

In [5]:
data = pd.read_csv("data.csv")

In [7]:
data.columns

Index(['Make', 'Model', 'Year', 'Engine Fuel Type', 'Engine HP',
       'Engine Cylinders', 'Transmission Type', 'Driven_Wheels',
       'Number of Doors', 'Market Category', 'Vehicle Size', 'Vehicle Style',
       'highway MPG', 'city mpg', 'Popularity', 'MSRP'],
      dtype='object')

In [11]:
data[data["Make"] == "BMW"]["MSRP"].mean()

61546.76347305389

In [14]:
data[data["Year"] >= 2015]["Engine HP"].isna().sum()

51

In [16]:
mean_hp_before = data["Engine HP"].mean()
mean_hp_before

249.38607007176023

In [18]:
hp_engine_after = data["Engine HP"].fillna(data["Engine HP"].mean())
mean_hp_engine_after = hp_engine_after.mean()
mean_hp_engine_after

249.38607007176

In [26]:
X = np.array(data[data["Make"] == "Rolls-Royce"][["Engine HP", "Engine Cylinders", "highway MPG"]].drop_duplicates())
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [30]:
XTX = X.T.dot(X)

In [33]:
invert = np.linalg.inv(XTX)
invert

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

In [34]:
invert.sum()

0.032212320677486125

In [39]:
y = [1000, 1100, 900, 1200, 1000, 850, 1300]
invert.dot(X.T).dot(y)

array([ 0.19989598, 31.02612262, 31.65378877])